#pragma once

#include "driver/gpio.h"

#define INKSIGHT_IDF_VERSION "0.1.1"

#define INKSIGHT_WIDTH 400
#define INKSIGHT_HEIGHT 300
#define INKSIGHT_ROW_BYTES (INKSIGHT_WIDTH / 8)
#define INKSIGHT_FRAME_BYTES (INKSIGHT_ROW_BYTES * INKSIGHT_HEIGHT)

#define RLCD_PIN_SCLK GPIO_NUM_11
#define RLCD_PIN_MOSI GPIO_NUM_12
#define RLCD_PIN_DC GPIO_NUM_5
#define RLCD_PIN_CS GPIO_NUM_40
#define RLCD_PIN_RESET GPIO_NUM_41
#define RLCD_PIN_TE GPIO_NUM_6

#define INKSIGHT_KEY_GPIO GPIO_NUM_18
#define INKSIGHT_BAT_ADC_GPIO GPIO_NUM_4

#define INKSIGHT_SPI_CLOCK_HZ (24 * 1000 * 1000)
#define INKSIGHT_DEFAULT_SLEEP_MINUTES 60
#define INKSIGHT_MIN_SLEEP_MINUTES 10
#define INKSIGHT_MAX_SLEEP_MINUTES 1440

#define INKSIGHT_WIFI_TIMEOUT_MS 20000
#define INKSIGHT_HTTP_TIMEOUT_MS 30000
#define INKSIGHT_HTTP_MAX_BODY (512 * 1024)

#define INKSIGHT_CONFIG_NAMESPACE "inksight"
#define INKSIGHT_CONFIG_VERSION 1
